### ISSUE TITLE
ParseError: expected 0x00 but got 0x02 at position 630668 (0x99f8c) in ep_railway_vehicle_common

### ISSUE THREAD

**Issue by PDiracDelta** [asheiduk/factorio-blueprint-decoder#5]
When using ./decode, I get the following error.
```
Traceback (most recent call last):
  File "./decode", line 2648, in <module>
    library = parse_blueprint_library(PrimitiveStream(f))
  File "./decode", line 2336, in parse_blueprint_library
    parse_library_objects(stream, global_index, book_item, library_version)
  File "./decode", line 2008, in parse_library_objects
    handler_result = handler(stream, index, library_version)
  File "./decode", line 2416, in parse_blueprint
    parse_entities(stream, index, result)
  File "./decode", line 2130, in parse_entities
    handler(stream, index, entity)
  File "./decode", line 1163, in eh_cargo_wagon
    ep_railway_vehicle_common(stream, index, entity)
  File "./decode", line 548, in ep_railway_vehicle_common
    stream.expect(0x00, 0x00)
  File "./decode", line 314, in expect
    raise ParseError(f"expected {expected:#04x} but got {actual:#04x} at position {position} ({position:#x})")
__main__.ParseError: expected 0x00 but got 0x02 at position 630668 (0x99f8c)
```
This blueprint is from an 1.0.0 game which I had initially started as 0.18 (attached).
[blueprint-storage.zip](https://github.com/asheiduk/factorio-blueprint-decoder/files/6487468/blueprint-storage.zip)

**Comment by asheiduk** [comment]
Your library contains some `cargo-wagon`. All train vehicles contain a random (?) id. So far I have encountered only IDs three bytes wide. Now I also know about four byte wide IDs. :-)

I've uploaded a new version - please try it and tell me if it worked for you.

**Comment by PDiracDelta** [comment]
That worked, thanks! You saved some _huge_ blueprints that somehow went bad when going from v1.0 to v1.1 (couldn't import them anymore).
